In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5,7])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 7]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
print(arr2)
arr2.reshape(1,5) # 1 row and 5 column
# print(arr2)

[1 2 3 4 5]


array([[1, 2, 3, 4, 5]])

In [18]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2.shape) #1D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)#2D array
print(arr2)
print(arr2.dtype)

(1, 5)
(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]
int64


In [15]:
arr3 = np.arange(0,10,2)
print(arr3)
arr3 = np.arange(0,10,2).reshape(5,1)
print(arr3)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.arange(10,60,10)
print(arr1,arr2)


# Element wise addition
print("addition", arr1 + arr2)

# Element wise substration
print("substration",arr1-arr2)

# Element wise Multiplication
print("multiplication", arr1 * arr2)

# Element wise division
print("Divistion", arr1 / arr2)

[1 2 3 4 5] [10 20 30 40 50]
addition [11 22 33 44 55]
substration [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
Divistion [0.1 0.1 0.1 0.1 0.1]


In [28]:
# Universal function
arr = np.array([1,2,3,4,5])

#square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sin
print(np.sin(arr))

#log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [31]:
# Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
print('picking 1 : \n',arr[0][0])
print("picking 3 4,7,8 8:\n",arr[0:2,2:])
print("picking 6 ,7,10,11:\n",arr[1:,1:3])

picking 1 : 
 1
picking 3 4,7,8 8:
 [[3 4]
 [7 8]]
picking 6 ,7,10,11:
 [[ 6  7]
 [10 11]]


In [36]:
print('picking 7 to 12')
arr[1:,2:]

picking 7 to 12


array([[ 7,  8],
       [11, 12]])

In [47]:
# Modify the elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [48]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [52]:
# Statistical Concepts
# To have mean of 0 and stadard deviation of 1
data = np.arange(1,6)
print(data)

# Calculate the mean
mean = np.mean(data)
std_dev = np.std(data)
print(f"mean : {mean}, standard devation : {std_dev}")

# Normalized data
normalized_data = (data - mean)/std_dev
print("Normalized data", normalized_data)

[1 2 3 4 5]
mean : 3.0, standard devation : 1.4142135623730951
Normalized data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [62]:
data = np.arange(1,11)
print(data)

# Mean
print("mean: ",np.mean(data))

#Median
print("Median : ",np.median(data))

# standard Deviation
print("Standard Deviation :",np.std(data))

# variance
print("Variance: ",np.var(data))

[ 1  2  3  4  5  6  7  8  9 10]
mean:  5.5
Median :  5.5
Standard Deviation : 2.8722813232690143
Variance:  8.25


In [71]:
data = np.arange(1,11)
print("Data : ",data)

print("Data > 5 :" ,data>5)
print("data => 2 and <= 8", (data >= 2) & (data <= 8))

Data :  [ 1  2  3  4  5  6  7  8  9 10]
Data > 5 : [False False False False False  True  True  True  True  True]
data => 2 and <= 8 [False  True  True  True  True  True  True  True False False]
